# Site settings
title: ldnrush
email: james@blackhatsquirrel.com
description: > # this means to ignore newlines until "baseurl:"
  Site description goes here sometimes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ldnrush.github.io" # the base hostname & protocol for your site
twitter_username: blackhatsquirrl
github_username:  bhsquirrel
##
# Build settings
markdown: kramdown
permalink: pretty
teaser: https://github.com/blackhatsquirrel/branding/blob/master/branding-white.png
#teaser: /assets/images/500x300.png
header:
  teaser: https://github.com/blackhatsquirrel/branding/blob/master/branding-white.png
#header:
  #teaser: /assets/images/my-awesome-post-teaser.jpg
